### ISSUE TITLE
[Bug] Add tests for updating table entries (users specifically)

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-metadata-mgmt#22]
### Pacifica Metadata Management version
`v0.2.0`

### Pacifica Core Software versions
`pacifica-metadata` `0.10.3`

### Scenario:
Trying to edit a user (middle name).

### Steps to Reproduce:
Open user (any) in users view, change middle initial or other field and hit save.

### Expected Result:
Changed value.

### Actual Result:
Getting a 400 on insert via PUT method in syslog.

**Comment by dmlb2000** [comment]
Pretty sure this is the same as #25
