### ISSUE TITLE
[Bug] Unable to update existing entry in projects table

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-metadata-mgmt#23]
### Pacifica Metadata Management version
`0.2.0`

### Pacifica Core Software versions
`>= 1.0`

### Scenario:
I am trying to update the abstract, title, short_name, science_theme, or project_type.

### Steps to Reproduce:
Have an existing adhoc project entry, try to just change the abstract and submit.

### Expected Result:
Changed any of the described fields without error.

### Actual Result:
I get a traceback error I am unable to copy to post here.

**Comment by dmlb2000** [comment]
Pretty sure #25 and this are the same bug.
