### ISSUE TITLE
[Bug] Unable to add metadata entry if no default date is set

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-metadata-mgmt#3]
Trying to add a new user group association from interface results in a traceback. I am unable to copy error message to post here but it amounts to:

```
  File "/opt/pacifica/lib/python2.7/site-packages/pacifica/metadata/rest/orm.py", line 155, in _insert
```

**Comment by GitBytes** [comment]
Comically if I hit cancel, it then is added to the table without error... Very odd behavior there..

*edit*
This is only the case if the traceback is encountered before attempting to cancel. If you cancel before encountering the traceback, the entry is not captured and the attempt is truly canceled..

**Comment by GitBytes** [comment]
There is also an issue on tables that involve the auto-generation of a UUID. It asks for a UUID primary key even though that should be autogenerated on save. For example, creating a new relationship between a project and instrument.

My main thought here is there are certain fields that should be auto-populated on save versus entered. These include UUIDs, Dates, maybe others but that would meet most of them I believe..

**Comment by GitBytes** [comment]
@dmlb2000 bump
This problem effectively breaks putting new entries on affected tables.

**Comment by dmlb2000** [comment]
@GitBytes So I've tried to add both a user/group and project/instrument entry and they both seemed to work with minimal input from the browser.

Please checkout the diff for the two pull requests and read the comments. I tried to comment exactly what I was simulating in the browsers. I'm currently testing both Firefox and Chrome.

**Comment by GitBytes** [comment]
@dmlb2000 will do
